;; -*- lexical-binding: t; -*-
(provide 'init-base)
(require 'init-f)
(require 'recentf)
(require 'saveplace)
(fset 'yes-or-no-p 'y-or-n-p)
(setq mode-on-or-off-list '((menu-bar-mode -1)
                            (global-display-line-numbers-mode t) 
                            (tool-bar-mode -1)
                            (scroll-bar-mode -1)
                            (show-paren-mode 1)
                            (global-hl-line-mode 1)
                            (save-place-mode 1)
                            (size-indication-mode 1)
                            (display-time-mode 1)
                            (global-prettify-symbols-mode 1)
                            (recentf-mode 1)))

(setq setting-list '((package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                                         ("melpa" . "http://elpa.emacs-china.org/melpa/")))
                     (ring-bell-function 'ignore)
                     (display-time-format "%H:%M")
                     (display-time-default-load-average nil)
                     (default-frame-alist '((height . 50 ) (width . 150)))
                     (make-backup-files nil)
                     (auto-save-default nil)
                     (recentf-max-menu-items 15)
                     (inhibit-splash-screen t)))

(setq default-setting-list '((cursor-type 'bar)
                             (save-place t)
                             (indent-tabs-mode nil)))
(mapcar (lambda (s)
          (eval (cons 'setq s)))
        setting-list)

(mapcar (lambda (s)
          (eval (cons 'setq-default s)))
        default-setting-list)

(mapcar (lambda (m) (eval m))
        mode-on-or-off-list)
